import '@/styles/reset.css'
import '@/styles/app.css'
import { signatureFont, serifFont } from '@/styles/fonts'
import { fontSizes } from '@/styles/sizes/font-sizes'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${signatureFont.variable} ${serifFont.variable}`}
      style={
        {
          '--h1-font-size': fontSizes.h1,
          '--h2-font-size': fontSizes.h2,
          '--h3-font-size': fontSizes.h3,
          '--p-font-size': fontSizes.p,
        } as React.CSSProperties
      }
    >
      <body>{children}</body>
    </html>
  )
}
